<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>

# Backpropagation Practice

## *Data Science Unit 4 Sprint 2 Assignment 2*

Using TensorFlow Keras, Implement a 3 input, 4 node hidden-layer, 1 output node Multilayer Perceptron on the following dataset:

| x1 | x2 | x3 | y |
|----|----|----|---|
| 0  | 0  | 1  | 0 |
| 0  | 1  | 1  | 1 |
| 1  | 0  | 1  | 1 |
| 0  | 1  | 0  | 1 |
| 1  | 0  | 0  | 1 |
| 1  | 1  | 1  | 0 |
| 0  | 0  | 0  | 0 |

If you look at the data you'll notice that the first two columns behave like an XOR gate while the last column is mostly just noise. Remember that creating an XOR gate was what the perceptron was criticized for not being able to learn.

This is your "Hello World!" of TensorFlow.

### Example TensorFlow Starter Code

```python 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential([
    Dense(3, activation='sigmoid', input_dim=2),
    Dense(1, activation='sigmoid')
])

model.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['acc'])

results = model.fit(X,y, epochs=100)

```

### Additional Written Tasks:
1. Investigate the various [loss functions](https://www.tensorflow.org/api_docs/python/tf/keras/losses). Which is best suited for the task at hand (predicting 1 / 0) and why? 
2. What is the difference between a loss function and a metric? Why might we need both in Keras? 
3. Investigate the various [optimizers](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers). Stochastic Gradient Descent (`sgd`) is not the learning algorithm dejour anyone. Why is that? What do newer optimizers such as `adam` have to offer? 

In [36]:
##### Your Code Here #####

import pandas as pd
data = {'x1': [0,0,1,0,1,1,0],
       'x2': [0,1,0,1,0,1,0],
       'x3': [1,1,1,0,0,1,0],
       'y': [0,1,1,1,1,0,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')



In [37]:
df

x1  x2  x3  y
0   0   0   1  0
1   0   1   1  1
2   1   0   1  1
3   0   1   0  1
4   1   0   0  1
5   1   1   1  0
6   0   0   0  0

1. import tensorflow
2. define a model
3. Compile a model
4. Fit the model
5. Evaluate the model

In [38]:
from tensorflow import keras
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import SGD

In [39]:
feats = list(df)[:-1]
feats


['x1', 'x2', 'x3']

In [40]:
X = df[feats].values
X

array([[0, 0, 1],
       [0, 1, 1],
       [1, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [1, 1, 1],
       [0, 0, 0]])

In [41]:
target = df['y']
target

0    0
1    1
2    1
3    1
4    1
5    0
6    0
Name: y, dtype: int64

In [42]:
y = target.values
y

array([0, 1, 1, 1, 1, 0, 0])

In [48]:
model = Sequential()
model.add(Dense(1, input_dim=3, activation ='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X,y, epochs=5)

Epoch 1/5
1/1 [==============================] - 0s 1ms/step - loss: 1.0239 - accuracy: 0.4286
Epoch 2/5
1/1 [==============================] - 0s 2ms/step - loss: 1.0230 - accuracy: 0.2857
Epoch 3/5
1/1 [==============================] - 0s 2ms/step - loss: 1.0221 - accuracy: 0.2857
Epoch 4/5
1/1 [==============================] - 0s 3ms/step - loss: 1.0212 - accuracy: 0.2857
Epoch 5/5
1/1 [==============================] - 0s 4ms/step - loss: 1.0203 - accuracy: 0.2857


In [44]:
#evaluate the model
scores = model.evaluate(X,y)
print(f'{model.metrics_names[1]}: {scores[1]*100}')

1/1 [==============================] - 0s 2ms/step - loss: 0.8160 - accuracy: 0.2857
accuracy: 28.57142984867096


### SGD 

In [45]:
model = Sequential()
model.add(Dense(1, input_dim=3, activation ='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer=SGD(), metrics=['accuracy'])
model.fit(X,y, epochs=5)

Epoch 1/5
1/1 [==============================] - 0s 1ms/step - loss: 0.8193 - accuracy: 0.5714
Epoch 2/5
1/1 [==============================] - 0s 1ms/step - loss: 0.8189 - accuracy: 0.5714
Epoch 3/5
1/1 [==============================] - 0s 2ms/step - loss: 0.8186 - accuracy: 0.5714
Epoch 4/5
1/1 [==============================] - 0s 2ms/step - loss: 0.8183 - accuracy: 0.5714
Epoch 5/5
1/1 [==============================] - 0s 1ms/step - loss: 0.8180 - accuracy: 0.5714


In [35]:
#evaluate the model
scores = model.evaluate(X,y)
print(f'{model.metrics_names[1]}: {scores[1]*100}')

1/1 [==============================] - 0s 2ms/step - loss: 0.6376 - accuracy: 0.5714
accuracy: 57.14285969734192


### Build a Tensor Keras Perceptron

Try to match the architecture we used on Monday - inputs nodes and one output node. Apply this architecture to the XOR-ish dataset above. 

After fitting your model answer these questions: 

Are you able to achieve the same results as a bigger architecture from the first part of the assignment? Why is this disparity the case? What properties of the XOR dataset would cause this disparity? 

Now extrapolate this behavior on a much larger dataset in terms of features. What kind of architecture decisions could we make to avoid the problems the XOR dataset presents at scale? 

*Note:* The bias term is baked in by default in the Dense layer.

In [ ]:
### Compare 

## Try building/training a more complex MLP on a bigger dataset.

Use TensorFlow Keras & the [MNIST dataset](http://yann.lecun.com/exdb/mnist/) to build the canonical handwriting digit recognizer and see what kind of accuracy you can achieve. 

If you need inspiration, the Internet is chalk-full of tutorials, but I want you to see how far you can get on your own first. I've linked to the original MNIST dataset above but it will probably be easier to download data through a neural network library. If you reference outside resources make sure you understand every line of code that you're using from other sources, and share with your fellow students helpful resources that you find.


### Parts
1. Gathering & Transforming the Data
2. Making MNIST a Binary Problem
3. Estimating your Neural Network (the part you focus on)

### Gathering the Data 

`keras` has a handy method to pull the mnist dataset for you. You'll notice that each observation is a 28x28 arrary which represents an image. Although most Neural Network frameworks can handle higher dimensional data, that is more overhead than necessary for us. We need to flatten the image to one long row which will be 784 values (28X28). Basically, you will be appending each row to one another to make on really long row. 

In [81]:
import numpy as np
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical

In [82]:
# input image dimensions
img_rows, img_cols = 28, 28

In [83]:
# the data, split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [84]:
x_train = x_train.reshape(x_train.shape[0], img_rows * img_cols)
x_test = x_test.reshape(x_test.shape[0], img_rows * img_cols)

# Normalize Our Data
x_train = x_train / 255
x_test = x_test / 255

In [85]:
# Now the data should be in a format you're more familiar with
x_train.shape

(60000, 784)

In [86]:
x_train[0].shape

(784,)

### Making MNIST a Binary Problem 
MNIST is multiclass classification problem; however we haven't covered all the necessary techniques to handle this yet. You would need to one-hot encode the target, use a different loss metric, and use softmax activations for the last layer. This is all stuff we'll cover later this week, but let us simplify the problem for now: Zero or all else.

In [87]:
import numpy as np

y_temp = np.zeros(y_train.shape)
y_temp[np.where(y_train == 0.0)[0]] = 1
y_train = y_temp

y_temp = np.zeros(y_test.shape)
y_temp[np.where(y_test == 0.0)[0]] = 1
y_test = y_temp

In [88]:
# A Nice Binary target for ya to work with
y_train

array([0., 1., 0., ..., 0., 0., 0.])

### Estimating Your `net

In [89]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten

import numpy as np

np.random.seed(812)

In [90]:
# https://keras.io/getting-started/sequential-model-guide/
model = Sequential()

In [91]:
model.add(Flatten(input_shape=(28,28)))
model.add(Dense(10,activation="softmax")) #Relu is valid option.

In [92]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x_train, y_train, epochs=10)

Epoch 1/10


ValueError: in user code:

    /opt/anaconda3/envs/U4-S1-NLP/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:571 train_function  *
        outputs = self.distribute_strategy.run(
    /opt/anaconda3/envs/U4-S1-NLP/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:951 run  **
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /opt/anaconda3/envs/U4-S1-NLP/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:2290 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /opt/anaconda3/envs/U4-S1-NLP/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:2649 _call_for_each_replica
        return fn(*args, **kwargs)
    /opt/anaconda3/envs/U4-S1-NLP/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:533 train_step  **
        y, y_pred, sample_weight, regularization_losses=self.losses)
    /opt/anaconda3/envs/U4-S1-NLP/lib/python3.7/site-packages/tensorflow/python/keras/engine/compile_utils.py:205 __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    /opt/anaconda3/envs/U4-S1-NLP/lib/python3.7/site-packages/tensorflow/python/keras/losses.py:143 __call__
        losses = self.call(y_true, y_pred)
    /opt/anaconda3/envs/U4-S1-NLP/lib/python3.7/site-packages/tensorflow/python/keras/losses.py:246 call
        return self.fn(y_true, y_pred, **self._fn_kwargs)
    /opt/anaconda3/envs/U4-S1-NLP/lib/python3.7/site-packages/tensorflow/python/keras/losses.py:1527 categorical_crossentropy
        return K.categorical_crossentropy(y_true, y_pred, from_logits=from_logits)
    /opt/anaconda3/envs/U4-S1-NLP/lib/python3.7/site-packages/tensorflow/python/keras/backend.py:4561 categorical_crossentropy
        target.shape.assert_is_compatible_with(output.shape)
    /opt/anaconda3/envs/U4-S1-NLP/lib/python3.7/site-packages/tensorflow/python/framework/tensor_shape.py:1117 assert_is_compatible_with
        raise ValueError("Shapes %s and %s are incompatible" % (self, other))

    ValueError: Shapes (32, 1) and (32, 10) are incompatible


In [71]:
scores = model.evaluate(x_test,y_test)
print("\n")
print("Validation Data Metrics:")
print(f"{model.metrics_names[0]}: {scores[0]}")
print(f"{model.metrics_names[1]}: {scores[1]*100}")

313/313 [==============================] - 0s 1ms/step - loss: 23.9521 - accuracy: 0.0312


Validation Data Metrics:
loss: 23.95206069946289
accuracy: 3.1199999153614044


## Stretch Goals: 

- Make MNIST a multiclass problem using cross entropy & soft-max
- Implement Cross Validation model evaluation on your MNIST implementation 
- Research different [Gradient Descent Based Optimizers](https://keras.io/optimizers/)
 - [Siraj Raval the evolution of gradient descent](https://www.youtube.com/watch?v=nhqo0u1a6fw)
- Build a housing price estimation model using a neural network. How does its accuracy compare with the regression models that we fit earlier on in class?